import gTAF_config


OCULUS_APK_PATH = gTAF_config.gTAF_home
OCULUS_APK_NAME = "build-twilight-android-twilight-android.164495530.apk"

BUTTON_CLASS = "android.widget.Button"
TWILIGHT_APP_LAUNCHER_ACTIVITY = "com.oculus.twilight/.TwilightLoginActivity"
FACEBOOK_APP_LAUNCHER_ACTIVITY = "com.facebook.katana/com.facebook.katana.LoginActivity"
BLUETOOTH_DISABLE_ACTIVITY = "android.bluetooth.adapter.action.REQUEST_DISABLE"
BLUETOOTH_ENABLE_ACTIVITY = "android.bluetooth.adapter.action.REQUEST_ENABLE"
LIST_VIEW_WIDGET = "android.widget.ListView"
TWILIGHT_APP_PACKAGE = "com.oculus.twilight"
SPINNER_RESOURCE_ID = "android:id/text1"
ANDROID_WIDGET_BUTTON = "android.widget.Button"
UNAME_SELECTOR_TEXT = "name@example.com"

SIGN_IN = "Sign in"
FORGOT_PASSWORD = "Forgot password?"
USERNAME = "appregress016@gmail.com"
PASSWORD = "Oculus@123"
FB_FIRST_NAME = "Test"
FB_SECOND_NAME = "app"
FB_USERNAME = "appre"
FB_PASSWORD = ""
NEXT = "Next"
SELECT_HEADSET = "Select Headset"
OCULUS_GO = "Oculus Go"
OCULUS_QUEST = "Oculus Quest"
OCULUS_QUEST_WELCOME_TEXT = "Welcome to Oculus Quest"
OCULUS_RIFT_S = "Oculus Rift S"
OCULUS_RIFT = "Oculus Rift"
SHOP_OCULUS = "Shop Oculus.com"
TERMS_OF_SERVICES = """By creating an account, you agree to the 
Oculus Terms of Service"""
PRIVACY_POLICY_LOGIN_SCREEN = """Learn more about how we collect, use and share your data in our 
Privacy Policy"""
FACEBOOK_CONTINUE_TEXT = "Continue with Facebook"
UNAME_TEXT = "name@example.com"
SETTINGS = "Settings"
ACCOUNT = "Account"
LOG_OUT = "Log Out"
POP_UP_LOGOUT = "LOG OUT"
CANCEL = "CANCEL"
CONTINUE = "Continue"
START = "Start"
TURN_HEADSET_TEXT = "Turn On Your Headset"
LOCATION_ACCESS = "Location Access"
PLUG_IN_HEADSET_TEXT = "Plug In Your Headset"
LOCATION_PUPUP_ACCESS_GRANT = "Allow Oculus to access this device's location?"
DENY = "Deny"
ALLOW = "Allow"
PAIRING_CODE = "Look into your headset for a 5-digit code in the lower right corner and enter it here."
LOOKING_FOR_HEADSET = "Looking For Headset"
ENABLE_LOCATION_SERVICES = "Enable Location Services"
GO_TO_SETTINGS = "Go To Settings"

START_NOW = "Start Now"
WELCOME_TO_OCULUS = "Welcome to Oculus"
TURN_ON_OCULUS = "Turn On Your Oculus Go"
BACK = "Back"

POWER = "Power"
PLUGIN = "Plug In Your Headset"
EXPLORE_RIFT_STORE = "Explore Rift Store"
OCULUS_RIFT_S_SETUP = "Oculus Rift S Setup"
WELCOME_RIFT = "Welcome to Rift"
PAIR_NEW_HEADSET = "Pair New Headset"
OCULUS_RIFT_SETUP = "Oculus Rift Setup"
PRESS_AND_HOLD_MSG = "Press and hold the power button for 2 seconds."
TURN_ON_HEADSET = "Turn On Your Headset"
ENABLE_BLUETOOTH = "Enable Bluetooth"
PAIRING = "Pairing"
HOME = "Home"
STORE = "Store"
EVENTS = "Events"
FRIENDS = "Friends"
WELCOME_BACK = "Welcome back, App"
RECOMMENDED = "Recommended For You"
TOP_FREE = "Top Free Apps"
SPOTLIGHT = "Spotlight"
NEW_AND_UPDATED = "New & Updated Apps We Love"
CATEGORIES = "Categories"
UPCOMING_EVENTS = "Upcoming Events"
MY_EVENTS = "My Events"
ADD_FRIENDS = "Add friends"
LINK_FACEBOOK = "Link to Facebook"
CHANGE_PASSWORD = "Change Oculus Password"
PLUGIN_OCULUS_GO = "Plug In Your Oculus Go"
